/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivasiRouteImport } from './routes/privasi'
import { Route as LinkWaJualanRouteImport } from './routes/link-wa-jualan'
import { Route as LinkWaCsRouteImport } from './routes/link-wa-cs'
import { Route as BulkRouteImport } from './routes/bulk'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivasiRoute = PrivasiRouteImport.update({
  id: '/privasi',
  path: '/privasi',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkWaJualanRoute = LinkWaJualanRouteImport.update({
  id: '/link-wa-jualan',
  path: '/link-wa-jualan',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkWaCsRoute = LinkWaCsRouteImport.update({
  id: '/link-wa-cs',
  path: '/link-wa-cs',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRoute = BulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bulk': typeof BulkRoute
  '/link-wa-cs': typeof LinkWaCsRoute
  '/link-wa-jualan': typeof LinkWaJualanRoute
  '/privasi': typeof PrivasiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bulk': typeof BulkRoute
  '/link-wa-cs': typeof LinkWaCsRoute
  '/link-wa-jualan': typeof LinkWaJualanRoute
  '/privasi': typeof PrivasiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bulk': typeof BulkRoute
  '/link-wa-cs': typeof LinkWaCsRoute
  '/link-wa-jualan': typeof LinkWaJualanRoute
  '/privasi': typeof PrivasiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bulk'
    | '/link-wa-cs'
    | '/link-wa-jualan'
    | '/privasi'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bulk'
    | '/link-wa-cs'
    | '/link-wa-jualan'
    | '/privasi'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/bulk'
    | '/link-wa-cs'
    | '/link-wa-jualan'
    | '/privasi'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BulkRoute: typeof BulkRoute
  LinkWaCsRoute: typeof LinkWaCsRoute
  LinkWaJualanRoute: typeof LinkWaJualanRoute
  PrivasiRoute: typeof PrivasiRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privasi': {
      id: '/privasi'
      path: '/privasi'
      fullPath: '/privasi'
      preLoaderRoute: typeof PrivasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link-wa-jualan': {
      id: '/link-wa-jualan'
      path: '/link-wa-jualan'
      fullPath: '/link-wa-jualan'
      preLoaderRoute: typeof LinkWaJualanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link-wa-cs': {
      id: '/link-wa-cs'
      path: '/link-wa-cs'
      fullPath: '/link-wa-cs'
      preLoaderRoute: typeof LinkWaCsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk': {
      id: '/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof BulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BulkRoute: BulkRoute,
  LinkWaCsRoute: LinkWaCsRoute,
  LinkWaJualanRoute: LinkWaJualanRoute,
  PrivasiRoute: PrivasiRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
